[book]
title = "技安Rust笔记"
authors = ["技安"]
description = "记录技安在学习Rust语言中的点点滴滴"
language = "zh-CN"
multilingual = false
src = "src"
git-repository-url = "https://github.com/EchoRust/JiAnRustNotes"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/EchoRust/JiAnRustNotes"